### ISSUE TITLE
Assignment 3 - Feedback do coleguinha

### ISSUE THREAD

**Issue by giorigor** [TS-puc-20201/assignment1n-ZeckCarvalhos#5]
OBS: Como ficamos com questões diferentes, vou responder como se eu tivesse realizado o assignment com as questões dele, mas da minha maneira.

### 1 - A complexidade ciclomática ficou igual?
Para ambos os casos, ficaria sim.
### 2 - Os casos de teste seguem a mesma lógica?
Não. O @ZeckCarvalhos realizou casos de teste não contemplados pelo grafo, criando uma cobertura de testes mais abrangente que a que eu faria.
### 3 - Qual linguagem a pessoa usou?
Java.
### 4 - Na linguagem, qual foi o framework?
JUnit.
### 5 - O formato de asserts ficou igual ou diferente?
Não. Ele criou asserts positivos e negativos para cada caso, enquanto eu gerei asserts únicos.
### 6 - Quais ferramentas o colega usou no trabalho em geral?
JUnit, para testes. CorelDraw para a criação do diagrama do grafo.
### 7 - Ele organizou a entrega como eu?
Não. O agrupamento do documento dele seguiu a ordem Questão > Exercício, enquanto eu agrupei meu documento por Exercício > Questão.

**Comment by ZeckCarvalhos** [comment]
Obrigado.
